#!/usr/bin/env python3
"""Generate install and upgrade SQL from shared, reviewable sources."""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parent.parent
parts = root / 'sql' / 'parts'
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
header = '-- Generated by scripts/generate-sql.py; edit sql/parts instead.\n'
catalog = (parts / 'types-and-catalog.sql').read_text()
metadata = (parts / 'metadata.sql').read_text()
shared = ''.join((parts / name).read_text() + '\n' for name in
                 ('management.sql', 'core-functions.sql', 'access.sql'))
upgrade = (parts / 'upgrade-preflight.sql').read_text()
outputs = {
    'pg_splitjson--0.2.0.sql': header + catalog + metadata + shared,
    'pg_splitjson--0.1.0--0.2.0.sql': header +
        '\\echo Use "ALTER EXTENSION pg_splitjson UPDATE TO \'0.2.0\'" to load this file. \\quit\n' +
        upgrade + metadata + shared,
}
for name, content in outputs.items():
    path = root / 'sql' / name
    if args.check:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f'{name} is stale; run scripts/generate-sql.py')
    else:
        path.write_text(content)
